### ISSUE TITLE
Error: Cannot find module ... @prisma/client/generator-build in @prisma/client 5.9.0+

### ISSUE THREAD

**Issue by tgrushka** [graphql-nexus/nexus-prisma#996]
When running `npx prisma build`, this plugin is broken by @prisma/client v5.9.0.

Force-downgrading to @prisma/client 5.8.1 fixes this error.

Since this is a prisma plugin, please document on web page: https://graphql-nexus.github.io/nexus-prisma/docs/usage
and probably in the README of this repo, too:
What version of prisma is currently supported?

This module load error is really not something we users can work around.

Thank you.
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Generator "nexus-prisma" failed:

node:internal/modules/cjs/loader:598
      throw e;
      ^
Error: Cannot find module '/Users/.../.../api/node_modules/@prisma/client/generator-build'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1181:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1169:15)
    at resolveExports (node:internal/modules/cjs/loader:591:14)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/.../.../api/node_modules/nexus-prisma/dist-cjs/lib/prisma-utils/externalToInternalDMMF.js:6:52)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/.../.../api/node_modules/@prisma/client/package.json'
}
Node.js v21.3.0
```

**Comment by frontendphil** [comment]
There is already a PR that fixes this: https://github.com/graphql-nexus/nexus-prisma/pull/985 "Just" needs to be merged :)
